# Generated by Django 4.1.5 on 2023-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sec', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopa', models.CharField(max_length=30)),
                ('apellidoMa', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('ciudad', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopa', models.CharField(max_length=30)),
                ('apellidoMa', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sec', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopa', models.CharField(max_length=30)),
                ('apellidoMa', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
