# Generated by Django 4.1.5 on 2023-11-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='telefono',
        ),
    ]
